### Vectors Overview:

In [1]:
import numpy as np

In [11]:
a = np.array([1, 2, 3])
print(a,'\n',type(a))

[1 2 3] 
 <class 'numpy.ndarray'>


In [12]:
np.array([1, 2, 3],dtype='float')

array([1., 2., 3.])

In [15]:
x = [1, 2, 3]
x_arr = np.array(x)
print(x, type(x))
print(x_arr, type(x_arr))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


In [16]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [17]:
np.ones(8)

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [18]:
np.arange(10, 50, 5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [19]:
import pandas as pd

In [31]:
data = [65, 70, 120, 35]
s = pd.Series(data)
print("Series:",s)

Series: 0     65
1     70
2    120
3     35
dtype: int64


In [27]:
x = s.values
print('vector:\n', x)
print("type of x:", type(x))

vector:
 [ 65  70 120  35]
type of x: <class 'numpy.ndarray'>


In [30]:
d = {'$$': [65, 70, 120, 35], 
     "2.Area": [50, 52, 80, 33],
     "3.Rooms":[3, 2, 1, 1], 
     "4.Floor":[5, 12, 10, 3],
     "5.Demo":[8, 4, 5, 10]}

df = pd.DataFrame(d)
print("DataFrame:\n", df)

DataFrame:
     $$  2.Area  3.Rooms  4.Floor  5.Demo
0   65      50        3        5       8
1   70      52        2       12       4
2  120      80        1       10       5
3   35      33        1        3      10


In [33]:
A = df.values
print("Matrtix:\n", A)

Matrtix:
 [[ 65  50   3   5   8]
 [ 70  52   2  12   4]
 [120  80   1  10   5]
 [ 35  33   1   3  10]]


In [35]:
x = A[1]
print("Second apartment vector:\n", x)
print("Type of x:", type(x))

Second apartment vector:
 [70 52  2 12  4]
Type of x: <class 'numpy.ndarray'>


In [36]:
y = A[:,0]
print("$$ vecotr :\n", y)

$$ vecotr :
 [ 65  70 120  35]


In [37]:
print("$$ of 3 apartment:", y[2])

$$ of 3 apartment: 120


In [39]:
print("Number of apartments = dim(x):", len(x))

Number of apartments = dim(x): 5


In [42]:
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])
print("a+b:", a+b)
print("2a:", 2*a)

a+b: [ 7  9 11]
2a: [2 4 6]


In [46]:
a_list = [1, 2, 3]
b_lsit = [6, 7, 8]
print("a+b", a_list+b_lsit)
print("2a:", 2*a_list)

a+b [1, 2, 3, 6, 7, 8]
2a: [1, 2, 3, 1, 2, 3]


In [47]:
a = np.array([1, 2, 3])
b = np.array([6, 7, 8])
c = np.array([1, 0, 1])

d = 2*a+2*b+3*c
print('linear combination:', d)

linear combination: [17 18 25]


In [49]:
s = np.dot(a, b)
print("scalar product:", s)

print("coordinate product:", a*b)

scalar product: 44
coordinate product: [ 6 14 24]


In [50]:
s1 = a@b
print("scalar product:", s1)

scalar product: 44


In [52]:
l = np.linalg.norm(a)
print("lenght of a:", l)

lenght of a: 3.7416573867739413


In [53]:
a_norm = a/np.linalg.norm(a)
print("a_norm:", a_norm)
print("length of a_norm:", np.linalg.norm(a_norm))

a_norm: [0.26726124 0.53452248 0.80178373]
length of a_norm: 1.0


In [58]:
a = np.array([1, 2, 1])
b = a*2
c = np.array([-1, 1, -1])

print("a:", a)
print("b:", b)
print("c:", c)

a: [1 2 1]
b: [2 4 2]
c: [-1  1 -1]


In [59]:
print("(a, b)", np.dot(a, b))
print("(a, c)", np.dot(a, c))
print("(b, c)", np.dot(b, c))

(a, b) 12
(a, c) 0
(b, c) 0


In [60]:
a = np.array([1, 0, 1])
b = np.array([0, 1, 0])
c = np.array([1, 0, -1])

print("a:", a)
print("b:", b)
print("c:", c)

a: [1 0 1]
b: [0 1 0]
c: [ 1  0 -1]


In [61]:
print("(a, b)", np.dot(a, b))
print("(a, c)", np.dot(a, c))
print("(b, c)", np.dot(b, c))

(a, b) 0
(a, c) 0
(b, c) 0


In [62]:
cl = np.array([1, 0, 4])
print("a:", a)
print("b:", b)
print("cl:", cl)

a: [1 0 1]
b: [0 1 0]
cl: [1 0 4]


In [63]:
print("(a, b):", a@b)
print("(b, c):", b@c)
print("(a, cl):", a@cl)

(a, b): 0
(b, c): 0
(a, cl): 5


#### Exerecises:

In [66]:
import pandas as pd

data = pd.DataFrame({
    '1.Rent': [65, 70, 120, 35, 40, 50, 100, 90, 85], 
    '2.Area': [50, 52, 80, 33, 33, 44, 80, 65, 65], 
    '3.Rooms':[3, 2, 1, 1, 1, 2, 4, 3, 2],
    '4.Floor':[5, 12, 10, 3, 6, 13, 8, 21, 5], 
    '5.Demo two weeks':[8, 4, 5, 10, 20, 12, 5, 1, 10], 
    '6.Liv.Area': [37, 40, 65, 20, 16, 35, 60, 50, 40]
})

In [67]:
data

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area
0      65      50        3        5                 8          37
1      70      52        2       12                 4          40
2     120      80        1       10                 5          65
3      35      33        1        3                10          20
4      40      33        1        6                20          16
5      50      44        2       13                12          35
6     100      80        4        8                 5          60
7      90      65        3       21                 1          50
8      85      65        2        5                10          40

##### Задание 3.3

Найдите вектор параметров квартиры номер 5 (нумерация квартир — с 1). Для преобразования DataFrame в массив numpy можно воспользоваться атрибутом values:

In [69]:
data.values[4]

array([40, 33,  1,  6, 20, 16])

##### Задание 3.4

Найдите вектор этажей всех квартир. Выберите координаты полученного вектора:

In [77]:
np.array((data['4.Floor']))

array([ 5, 12, 10,  3,  6, 13,  8, 21,  5])

##### Задание 3.5

Вычислите вектор нежилой площади. Выберите координаты полученного вектора:

In [80]:
np.array(data['2.Area'] - data['6.Liv.Area'])

array([13, 12, 15, 13, 17,  9, 20, 15, 25])

##### Задание 3.6

Пусть в первой квартире один просмотр занимает 10 минут, во второй — 20 минут, в третьей — полчаса, в четверой — 15 минут, в пятой — 5 минут, в шестой — 40 минут, в седьмой — 20 минут, в восьмой — 8 минут и в девятой — 20 минут.

Найдите продолжительность просмотров в минутах во всех квартирах за две недели.

In [81]:
data['7.Demo Time'] = np.array([10, 20, 30, 15, 5, 40, 20, 8, 20])

In [82]:
data

1.Rent  2.Area  3.Rooms  4.Floor  5.Demo two weeks  6.Liv.Area  7.Demo Time
0      65      50        3        5                 8          37           10
1      70      52        2       12                 4          40           20
2     120      80        1       10                 5          65           30
3      35      33        1        3                10          20           15
4      40      33        1        6                20          16            5
5      50      44        2       13                12          35           40
6     100      80        4        8                 5          60           20
7      90      65        3       21                 1          50            8
8      85      65        2        5                10          40           20

In [85]:
time = np.array(data['5.Demo two weeks']*data['7.Demo Time'])
time

array([ 80,  80, 150, 150, 100, 480, 100,   8, 200])

In [87]:
np.sum(time)

1348

##### Задание 3.7:

Составьте линейную комбинацию векторов  и  с коэффициентами 2 и -3. Выберите координаты полученного вектора:

In [89]:
u = np.array([3,0,1,1,1])
v = np.array([0,1,0,2,-2])
w = np.array([1,-4,-1,0,-2])

In [91]:
s= 2*v + (-3)*w
s

array([-3, 14,  3,  4,  2])

##### Задание 3.8

Будет ли эта комбинация ортогональна вектору ?

In [92]:
np.dot(s, u)

0